### ISSUE TITLE
Error downloading one maptile causes crash

### ISSUE THREAD

**Issue by kf6kjg** [kf6kjg/Anaximander#13]
Looks like all the active CURL calls complete, and the "Download took" message is played back, but if one of the CURL calls fails, the rest of the process is done for.  Anaximander should just skip over that failure and keep moving.

**Comment by Vinhold** [comment]
20160506T155519[tilegrabber]N: * Writing to F:\Websites\GospelLearningCenter\wwwroot\GospelWorld\newtiles/999-996-1.jpg
20160506T155535[tilegrabber]N: Download took 21 seconds for 30 regions, resulting in 0.7 seconds per region on average.
20160506T155535[app]N: Program took 21 seconds.
std.net.curl.CurlException@std\net\curl.d(3605): Couldn't connect to server on handle 1F25A90
----------------
0x000000013FC00915
0x000000013FCCB370
0x000000013FCBE5FF
0x000000013FCCB63B
0x000000013FCB6452
0x000000013FC3FFBD
0x000000013FC3FD14
0x000000013FC3F704
0x000000013FC3EF9D
0x000000013FC3E908
0x000000013FC31F23
0x000000013FCDC077
0x000000013FCC5AD5
0x000000013FCC540F
0x000000013FCAC2B7
0x000000013FCAC444
0x000000013FCAC3B8
0x000000013FCED36D
0x000000013FCDB9CB
0x000000013FD06127
0x000000013FD061BB
0x00000000773159ED in BaseThreadInitThunk
0x000000007744B371 in RtlUserThreadStart

**Comment by kf6kjg** [comment]
The issue is that there's a region in the database that is not actually online.  Anaximander needs to detect and bypass this.
